### ISSUE TITLE
Build cannot find pthread symbols

### ISSUE THREAD

**Issue by leonheldattoradex** [torizon/aktualizr-deb#1]
https://github.com/torizon/aktualizr-deb/actions/runs/7758227298/job/21159498972#step:3:2980

Maybe missing dependency against libc6-dev?

**Comment by leonheldattoradex** [comment]
It seems like https://github.com/torizon/aktualizr-deb/commit/56a3ed0dc5d6960f2bf74f43a5d55d55333b2fd6 didn't properly copy the submodules leading to errors in eg, google test https://github.com/torizon/aktualizr-deb/actions/runs/7758227298/job/21159498972#step:3:1626

**Comment by leonheldattoradex** [comment]
Ok so it's the submodules in https://github.com/torizon/aktualizr-deb/tree/toradex/ubuntu/focal/third_party.

https://github.com/torizon/aktualizr-deb/pull/2

@charles2910 feel free to force-rebase and add the workflows.

**Comment by charles2910** [comment]
Thanks, @leonheldattoradex.

I did reimport the tarball and cherry-picked your commit adding the workflow. It's passing now :- )

Seems that gbp doesn't like subdirs  with .git in them.
