### ISSUE TITLE
Split aktualizr in multiple binary packages

### ISSUE THREAD

**Issue by charles2910** [torizon/aktualizr-deb#6]
we could improve things to make it more general (split the package in aktualizr-torizon, libaktualizr-torizon (shared library), libaktualizr-dev (header and pkg-config files) and aktualizr-tools (for other interesting tools)).

This is the approach commonly used in Debian so we can transition libraries (ABI version changes) easily.

**Comment by charles2910** [comment]
This can only be done correctly if the shared library has a versioned SONAME

**Comment by leonheldattoradex** [comment]
Close because it's out-of-scope for this package.
If we ever need this (ie, other packages/applications linking against libaktualizr we might prioritize it).
